vich_uploader:
    db_driver: orm

    mappings:
        images:
            uri_prefix: /upload/img
            upload_destination: '%kernel.project_dir%/public/upload/img'
            delete_on_remove: true
            delete_on_update: true
            inject_on_load: false
